import { render, screen } from '@testing-library/react';
import '@testing-library/jest-dom';
import OverviewTab from './OverviewTab';

describe('OverviewTab', () => {
  const renderOverviewTab = () => {
    return render(<OverviewTab />);
  };

  it('renders the AI-Generated Job Summary section', () => {
    renderOverviewTab();
    expect(screen.getByText('AI-Generated Job Summary')).toBeInTheDocument();
  });

  it('renders the job summary placeholder content', () => {
    renderOverviewTab();
    expect(screen.getByText('This is a placeholder for the job summary generated by AI.')).toBeInTheDocument();
  });

  it('renders the Day in the Life section', () => {
    renderOverviewTab();
    expect(screen.getByText('Day in the Life')).toBeInTheDocument();
  });

  it('renders the day in the life content', () => {
    renderOverviewTab();
    expect(screen.getByText('A typical day in this role might include collaborating with a team, writing code, and attending meetings.')).toBeInTheDocument();
  });

  it('renders the Key Details section', () => {
    renderOverviewTab();
    expect(screen.getByText('Key Details')).toBeInTheDocument();
  });

  it('renders salary information', () => {
    renderOverviewTab();
    expect(screen.getByText('Salary: $120,000')).toBeInTheDocument();
  });

  it('renders location information', () => {
    renderOverviewTab();
    expect(screen.getByText('Location: Remote')).toBeInTheDocument();
  });

  it('renders key details as a list', () => {
    renderOverviewTab();
    const list = screen.getByRole('list');
    expect(list).toBeInTheDocument();
    const listItems = screen.getAllByRole('listitem');
    expect(listItems).toHaveLength(2);
  });

  it('applies correct styling to section headers', () => {
    renderOverviewTab();
    const headers = screen.getAllByText(/AI-Generated Job Summary|Day in the Life|Key Details/);
    headers.forEach(header => {
      expect(header).toHaveClass('font-bold', 'mb-2');
    });
  });

  it('applies correct styling to content text', () => {
    renderOverviewTab();
    const contentTexts = screen.getAllByText(/This is a placeholder|typical day|A typical day/);
    contentTexts.forEach(text => {
      expect(text).toHaveClass('text-gray-700');
    });
  });

  it('renders all content in correct order', () => {
    renderOverviewTab();
    const container = screen.getByText('AI-Generated Job Summary').parentElement;
    expect(container).toBeInTheDocument();

    // Check that sections appear in expected order
    const sections = ['AI-Generated Job Summary', 'Day in the Life', 'Key Details'];
    sections.forEach(section => {
      expect(screen.getByText(section)).toBeInTheDocument();
    });
  });
});