export default function OverviewTab() {
  return (
    <div>
      <div className="font-bold mb-2">AI-Generated Job Summary</div>
      <div className="mb-4 text-gray-700">This is a placeholder for the job summary generated by AI.</div>
      <div className="font-bold mb-2">Day in the Life</div>
      <div className="mb-4 text-gray-700">A typical day in this role might include collaborating with a team, writing code, and attending meetings.</div>
      <div className="font-bold mb-2">Key Details</div>
      <ul className="text-gray-700">
        <li>Salary: $120,000</li>
        <li>Location: Remote</li>
      </ul>
    </div>
  );
}
